server:
  port: 9090
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
      
zuul:
  prefix: /api
  routes:
    test:
      path: /redirect/**
      url: http://example.org
    customer-by-address:
      path: /customer-by-address/**
      url: http://localhost:9098
    customer-by-service:
      path: /customer-by-service/**
      serviceId: customer-service
      
spring:
  application:
    name: zuul-server