/*Drop database if it exists*/
DROP USER playerone CASCADE;

/*Create the database*/
CREATE USER playerone
IDENTIFIED BY p4ssw0rd
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 10M ON users;

GRANT connect to playerone;
GRANT resource to playerone;
GRANT create session to playerone;
GRANT CREATE TABLE TO playerone;
GRANT CREATE view To playerone;

/*Connect as new user, otherwise will use current user*/
CONNECT playerone/p4ssw0rd;

/*Create tables*/
CREATE TABLE GENRE (
    GENRE_ID INTEGER,
    GENRE_NAME VARCHAR2(50),
    CONSTRAINT PK_GENRE PRIMARY KEY (GENRE_ID)
);

CREATE TABLE playerone.GAME (
    GAME_ID INTEGER,
    GAME_NAME VARCHAR2(100),
    GENRE_ID INTEGER,
    CONSTRAINT PK_GAME PRIMARY KEY (GAME_ID)
);

/*Create foreign keys*/
ALTER TABLE GAME ADD CONSTRAINT FK_GENRE_ID FOREIGN KEY (GENRE_ID)
    REFERENCES GENRE (GENRE_ID) ON DELETE CASCADE;

/*Create sequences*/
CREATE SEQUENCE SQ_PK_GENRE
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE SQ_PK_GAME
START WITH 1
INCREMENT BY 1;
/

/*Create triggers*/
CREATE OR REPLACE TRIGGER TR_INSERT_GENRE
BEFORE INSERT ON GENRE
FOR EACH ROW
BEGIN
    SELECT SQ_PK_GENRE.NEXTVAL INTO :NEW.GENRE_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TR_INSERT_GAME
BEFORE INSERT ON GAME
FOR EACH ROW
BEGIN
    SELECT SQ_PK_GAME.NEXTVAL INTO :NEW.GAME_ID FROM DUAL;
END;
/

/*Create Views*/
CREATE OR REPLACE VIEW VW_GAME_GENRE AS
    SELECT GENRE_NAME, GAME_NAME 
    FROM GENRE INNER JOIN GAME ON GENRE.GENRE_ID = GAME.GENRE_ID;
/
    
/*Create Index*/
CREATE INDEX IX_index
    ON GAME (GAME_NAME);
/


/*Populating tables*/
INSERT INTO GENRE (GENRE_NAME) VALUES ('FPS');
INSERT INTO GENRE (GENRE_NAME) VALUES ('RPG');
INSERT INTO GENRE (GENRE_NAME) VALUES ('Strategy');

INSERT INTO GAME (GAME_NAME, GENRE_ID) VALUES ('Fable', 2);
INSERT INTO GAME (GAME_NAME, GENRE_ID) VALUES ('Pong', 3);
INSERT INTO GAME (GAME_NAME, GENRE_ID) VALUES ('Overwatch', 1);








